coinbase/odin

.gitignore
Dockerfile
Gopkg.lock
Gopkg.toml
README.md
aws/aws.go
aws/mocks/mock_asg.go
deployer/client/client.go
deployer/client/client_test.go
deployer/client/deploy.go
deployer/client/deploy_test.go
deployer/client/halt.go
deployer/handlers.go
deployer/handlers_test.go
deployer/intergration_test.go
deployer/machine.go
deployer/models/mocks.go
deployer/models/release.go
deployer/models/release_test.go
deployer/models/service.go
deployer/models/service_resources.go
deployer/models/service_resources_test.go
deployer/models/service_test.go
odin.go
releases/deploy-test-release.json
releases/null-release.json
releases/null-release.json.userdata
resources/deploy-test-resources.rb

Also:
1. expanded the ability for the different paths an instance profile an have, to allow for default and per project and per config profiles. This should make it easier to use and develop with Odin.
2. deploy only with files now since userdata is no longer in the release
3. adding `odin` prefix to roles so that external services can directly reference roles assigned by odin.

[Refactor] Upload KMS encrypted userdata to S3, to limit userdata access

---

aws/alb/target_group.go
aws/ami/image.go
aws/asg/asg.go
aws/elb/elb.go
aws/mocks/mock_ec2.go
aws/sg/security_group.go
aws/subnet/subnets.go
deployer/client/client.go
deployer/client/deploy.go
deployer/client/halt.go
deployer/handlers.go
deployer/machine.go
deployer/models/autoscaling.go
deployer/models/mocks.go
deployer/models/policy.go
deployer/models/release.go
deployer/models/service.go
deployer/models/service_resources.go
odin.go
releases/deploy-test-release.json

KMS key is entirely on the client not on the deployer
This PR also:
1. makes some better error messages.
1. Allows for ASGs to be tagged ReleaseId or ReleaseID
1. fixes Security Group and Subnet querying
1. allows selecting the step function to deploy to on the command line using envvar

[Refactor] no need to send kms keys to odin

---

Gopkg.lock
deployer/models/autoscaling.go
deployer/models/autoscaling_test.go
deployer/models/service.go
deployer/models/service_test.go

Make health_check_grace_period default to timeout, otherwise validate it by making sure it is not greater than timeout if manually specified.

Default health check grace period

---

deployer/models/autoscaling.go
deployer/models/autoscaling_test.go
deployer/models/policy.go
deployer/models/policy_test.go

An issue was raised where policies wont necessarily have unique names which can cause issues.
This will:
1. generate more unique names for services that do specify names
2. be invalid if two policies don't have unique names

[Fix] ensure policy name uniqness

---

.gitignore
aws/asg/asg_input.go
aws/mocks/mock_asg.go
deployer/models/service.go

* Enables metric collection for autoscaling groups. Does not make it configurable.
* Sets the default to propagate tags on autoscaling groups (the default).
Reference:
* API: https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_EnableMetricsCollection.html
* SetEnabledMetrics: https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#Group.SetEnabledMetrics
* EnabledMetric: https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#EnabledMetric
Local tests:
```
go test ./...
?   	github.com/coinbase/odin	[no test files]
ok  	github.com/coinbase/odin/aws	(cached)
ok  	github.com/coinbase/odin/aws/alarms	(cached)
ok  	github.com/coinbase/odin/aws/alb	(cached)
ok  	github.com/coinbase/odin/aws/ami	(cached)
ok  	github.com/coinbase/odin/aws/asg	(cached)
ok …
```

[odin] enable autoscaling metrics; set tag propagate

---

aws/asg/asg.go

Since we still sometimes see the detach timeout getting exhausted in production, this is a further stopgap measure until a better solution is added.

Increase detach wait time to 3 minutes max

---

aws/alb/target_group.go
aws/alb/target_group_test.go
aws/asg/asg.go
aws/aws.go
aws/elb/elb.go
aws/mocks/mock_alb.go
aws/sg/security_group.go
deployer/handlers_test.go
deployer/models/mocks.go
deployer/models/service_resources.go

As we expand the use of target groups, we will likely want to deploy multiple projects behind a single ALB. To do this, we need to allow a target group to nominate the service that should be allowed to attach to it, if it differs from the parent project. 
We do this via an `AllowedService` tag on the target group.

[FEATURE] Allow TG's to nominate allowed services

---

deployer/handlers.go
deployer/intergration_test.go
go.mod
go.sum

This PR updates to the latest version of Step which handles locking per release and adds arbitrary metadata to the release.
This allows admins to redeploy a release if we delete the lock in the release directoy and it is less than 10 days old.
Ref https://github.com/coinbase/step/pull/45

[Update] updating to latest step version with good locking and metadata

---

deployer/handlers.go
deployer/helpers_test.go
deployer/intergration_test.go
deployer/models/mocks.go
deployer/models/release.go
deployer/models/release_resources.go
deployer/models/release_resources_test.go
deployer/models/release_safe.go
deployer/models/release_safe_test.go

Safe Release flag `safe_release ` is used to compare the previous release for dangerous changes and fail the deploy if such a change is detected.
This is backwards compatible because the flag is defaulted to false and no new validations are added without the new flag set true.

[Feature] Safe Release

---

deployer/machine.go
deployer/models/release_safe.go
deployer/models/release_safe_test.go

CLOUD-671 & DEVPROD-664
This PR:
1. removes image from safety checks to quickly allow security updates.
2. increases wait time after disconnect.

[Fix] remove image from safety checks, increase ALB timeout

---

deployer/models/release_safe.go
deployer/models/release_safe_test.go
scripts/bootstrap_deployer

Appending all `safe_release` errors together so that all issues can be addressed at once rather than iteratively over multiple failed deploys.

[Fix] returning all safe_release errors at the same time

---

aws/asg/asg.go
aws/asg/asg_test.go
deployer/machine.go
deployer/models/release.go
deployer/models/release_resources.go

Due to checking a performance optimisation we never actually were checking if the instances were detached. This PR fixes that and ensures that the instances are detached. 
This could increase deploy times significanty, at least by the `deregistration_delay` amount, which by default is 300. So all deploys that have a target group may increase by up to 5 minutes.

[Fix] issue with detecting detached.

---

aws/asg/asg.go
aws/asg/asg_test.go
aws/mocks/mock_asg.go
deployer/models/release_resources.go

This PR:
1. Adds ELB checking for detached before finishing the deploy
2. Reports in the returned error the Actual ELBs which are not being removed.

[Fix] Also checking ELBs for detached and better error reporting

---

deployer/machine.go

When an ASG is set to EC2 health checks, its instances only check is that the instance is running. If it has a longer boot time Odin may succeed a deploy before the instance has a chance to shutdown because of bad userdata.
Long term Odin should should respect the HealthCheckGracePeriod for each instance (When EC2 health checks are there) but at the moment this is a blunt fix for now.

[Fix] Blunt fix to increase initial wait time to allow instance to self terminate

---

aws/mocks/mock_ec2.go
aws/pg/placement_group.go
aws/pg/placement_group_test.go
deployer/models/mocks.go
deployer/models/service.go
deployer/models/service_test.go

This feature will create/use placement groups for AutoScalingGroups. This PR: 
1. Creates the placement group if not yet created (if created validates the prefix is `odin/<project_name>/<config_name>`)
2.  If already existing checks the values provided are the same to make sure we know the values. (we don't do any kind of updating because might cause bad situations where two projects update the placemnet group causing lots of termed instances) 
There are many caveats to using placement groups when deploying, read about them https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/placement-groups.html#placement-groups-cluster

[Feature] Create/Use placement groups for deploys.

---

deployer/machine.go

We observed yesterday that odin ends up waiting for a long time while polling for successful ALB detaches. This is partially due to the default exponential backoff setting of AWS step functions, [documented here](https://docs.aws.amazon.com/step-functions/latest/dg/concepts-error-handling.html). This change removes the exponential backoff in 3 places that we don't need it.

[fix] disable exponential backoff in places we don't want it

---

aws/mocks/mock_asg.go
deployer/handlers.go
deployer/models/release_resources.go
deployer/models/release_resources_test.go
deployer/models/service.go
deployer/models/service_test.go

This PR will reset the desired capacity of the Autoscaling groups back to the value without spread. This is because sometimes the value of the desired capacity can ratchet up over many deploys and 1) cost more 2) make deploys take longer 3) cause other errors related to resource exhaustion. 
The main danger with this PR is that if there is an autoscaling event on either the new or old ASG during the deploy this will not take that into account when resetting the instance count.
This has been tested in development.

[Fix] reset the desired capacity to remove the spread

---

aws/mocks/mock_asg.go
deployer/helpers_test.go
deployer/intergration_test.go
deployer/models/release.go
deployer/models/release_resources.go
go.mod
scripts/graph

This will let a user select how Odin detaches its instances from ELBs. In this PR we default to what we typically do, but you could either:
1. Skip detaching all together
2. Call Detach, but skip checking for when detach finishes.
The first is what the old behaviour of Odin was, but can be unsafe with lots of traffic. The second can be useful if we want to start bringing down the instances while it is detaching. Which is useful for long lived connections.

[Feature] Detach Strategies

---

deployer/models/strategy.go
deployer/models/strategy_test.go

the /4 in the method should always return greater than 0 otherwise services with less than 4 instances will get stuck.

[Fix] fixing small numbers of ramp up value

---

deployer/models/autoscaling.go
deployer/models/strategy.go
deployer/models/strategy_test.go

This adds a variation on the existing 25% rollout strategy with a 10% rate.

Add 10PercentStepRolloutNoCanary strategy

---

deployer/machine.go

We're seeing long delays in deploy halting, up to 7 minutes. This PR reduces the retry count / period to limit the detach wait time to 1 minute.

Speed up DetachForFailure step

---

deployer/machine.go
deployer/models/release_resources.go

After recent changes to retry less times on DetachForFailure, this error was being hit from time to time and would overwrite the error object on the release which was responsible for sending the deploy into the failure state in the first place. As we don't care to wait for detach to finish here, we increase the wait after this to 60s. Other errors in DetachForFailure would still behave the same way, which seems like what we'd want here as they are not expected like this one.

Fix DetachError issue

---

.circleci/config.yml
deployer/models/autoscaling.go
deployer/models/release_resources_test.go
deployer/models/service.go
deployer/models/strategy.go
deployer/models/strategy_test.go

This refactors the strategies to make  them more contained within the model, 
This also adds the "10AtATimeNoCanary" and "20..." strategies that will always try to deploy a set increment at a time until all are deployed

[Refactor/feature] refactor strategies and add 10AtATime

---

aws/asg/asg.go
aws/mocks/mock_asg.go

Although Odin does not require an Auto Scaling Group's MaxSize, third party code that imports Odin's modules may need it.

Add MaxSize to Odin's ASG struct
